# Generated by Django 2.0 on 2020-03-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='summmary',
            field=models.CharField(blank=True, max_length=1024, verbose_name='摘要'),
        ),
    ]
