# Generated by Django 2.0 on 2020-04-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pv',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='uv',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
