# Generated by Django 2.0 on 2020-03-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200325_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='desc',
            field=models.CharField(default='', max_length=255, verbose_name='描述'),
        ),
    ]
